package com.claude.cicd.payment.domain;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * Payment domain model.
 *
 * <p>Instances are always created through {@link #create(BigDecimal, Currency, String)} so
 * that the identifier, initial status, and creation timestamp are generated by the
 * application rather than supplied by a caller.
 */
public record Payment(
        UUID id,
        BigDecimal amount,
        Currency currency,
        PaymentStatus status,
        String description,
        Instant createdAt) {

    public Payment {
        Objects.requireNonNull(id, "id must not be null");
        Objects.requireNonNull(amount, "amount must not be null");
        if (amount.signum() <= 0) {
            throw new IllegalArgumentException("amount must be greater than zero");
        }
        Objects.requireNonNull(currency, "currency must not be null");
        Objects.requireNonNull(status, "status must not be null");
        Objects.requireNonNull(createdAt, "createdAt must not be null");
    }

    /**
     * Creates a new payment in its initial {@link PaymentStatus#CREATED} state.
     */
    public static Payment create(BigDecimal amount, Currency currency, String description) {
        return new Payment(UUID.randomUUID(), amount, currency, PaymentStatus.CREATED, description, Instant.now());
    }
}
